Issue 08 Create endpoint get products by id and create endpoint to update products
elbarbaro/ecommerceapp-nursery-garden pull request #11
Opened 2023-12-02 20:39 UTC by raisa16

Implement response handler

2023-12-05 00:00 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/exceptions/RestExceptionHandler.java
> +@ControllerAdvice()
Borremos esos paréntesis de más

2023-12-05 00:17 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/ProductController.java
> +
Hagamos que el manejo de la excepción sea por parte del exception handler nada más lo cual lo método del controller por eso hay que crear una excepción propia y no una a base del framework
![Screen Shot 2023-12-04 at 18 08 54](https://github.com/elbarbaro/ecommerceapp-nursery-garden/assets/9300957/bbb8d7b7-2890-4899-aac8-860190efd17c)
Esto permitirá el eliminar la responsabilidad al controller y dejarlo en el response error handler

2023-12-05 00:17 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/ProductServiceImpl.java
> +            Category category = categoryRepository.findById(productDTO.getCategoryId()).orElseThrow(EntityNotFoundException::new);
Lo mismo para la categoría

2023-12-05 00:17 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/ProductServiceImpl.java
> +        Product product = productRepository.findById(id).orElseThrow(EntityNotFoundException::new);
Busquemos el generar una excepción propia para identificar de manera específica una entidad en este caso el producto, no una general.

2023-12-07 00:37 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/exceptions/RestExceptionHandler.java
> +@ControllerAdvice()
Hola, ya fueron borrados en el commit mas reciente

2023-12-07 00:38 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/ProductController.java
> +
Ya cree las excepciones propias y removi la implementacion en el controller

2023-12-08 16:08 UTC, elbarbaro requested changes

2023-12-08 16:08 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/exceptions/ErrorResponse.java
> +public class ErrorResponse {
Al utilizar esta clase para crear el objeto de respuesta de la API cuando hay un error. es importante seguir la misma convención de nombramiento snake_case. Hace falta agregar algo para lograr eso al momento de deserializar.

2023-12-08 16:08 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/ProductServiceImpl.java
> +        productDb.setName(productDto.getName());
Es este bloque falta agregar una nueva fecha de actualización evidenciando que los datos se actualizaron en cierto tiempo en el producto.

2023-12-09 04:17 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/exceptions/ErrorResponse.java
> +public class ErrorResponse {
Hola Leo agregue el snake_case  en la clase ErrorResponse y actualize la fecha para la operacion update, tambien modifique la sintaxis de una excepcion arrojada para que fuera como las demas.

2023-12-09 18:27 UTC, elbarbaro approved these changes

2023-12-09 18:57 UTC, merged