.feature/issue-19/Create-product-images-endpoint-to-associate-images-uploaded-on-S3-part3
elbarbaro/ecommerceapp-nursery-garden pull request #20
Opened 2024-02-24 04:02 UTC by raisa16

Update process to accept multiple image files, add validation to accept max 3 images

2024-02-24 18:55 UTC, elbarbaro requested changes

2024-02-24 18:55 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/ProductImageServiceImpl.java
> +                productImage = new ProductImage();
La instanciación de un objeto puede suceder después de obtener la url de la imagen. El código actual genera la instanciación primero y luego asigna los atributos pero si falla no se llegaría a esta parte obteniendo uso de recursos no utilizados.

2024-02-24 18:55 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/validators/FileValidator.java
>              return result;
Viendo con detalle. Sería mejor sólo hacer la asignación para que el caso de que hubiera más de un error en la validación del archivo se pueda regresar todos los posibles errores y no sólo el primero que encuentre. Haciendolo de esta forma con el return sólo se encuentra con el primero y se agrega al `constraintValidatorContext`

2024-03-01 02:06 UTC, elbarbaro requested changes

2024-03-01 02:06 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/validators/FileValidator.java
> +            if (file.getSize() > MAX_SIZE) {
Remover esta validación porque está controlada a través del property del `spring.servlet.multipart.max-file-size` de spring servlets

2024-03-01 02:06 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/ProductImageServiceImpl.java
> +                productImage.setProductId(product);
Renombrar el nombre del atributo ya que un productId no es un producto. En el ejemplo estamos seteando un objeto producto en un método que da entender que tenemos que mandarle un productId que sería un número. Cambiar esto

2024-03-01 02:06 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/ProductImageServiceImpl.java
> +                productImage.getId();
Remover este llamado

2024-03-01 02:06 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/filestore/FileStoreServiceImpl.java
> +
Es importante controlar las posible excepciones a través un try-catch para poder darle un nombre diferente al error de acuerdo al proceso que se está ejecutando logrando notificar al cliente que ocurrió un error pero está controlado. Para este caso crear una excepción que será lanzada la cual permita regresar un código de respuesta 502 Bad Gateway. El nombre de la excepción se descriptivo a la etapa del proceso que falló

2024-03-14 23:15 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/exceptions/RestExceptionHandler.java
> +import org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException;
Esta importación borrarla por la razón que no se está utilizando

2024-03-15 00:49 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/exceptions/RestExceptionHandler.java
> +import org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException;
listo

2024-03-15 02:24 UTC, elbarbaro approved these changes

2024-03-15 02:24 UTC, merged