create endpoint to register new user
elbarbaro/ecommerceapp-nursery-garden pull request #24
Opened 2024-03-29 02:17 UTC by raisa16

create User, UserController, UserDto, UserRepository, UserResponse, UserService, UserServiceImpl, UserType, UserTypeService, UserTypeServiceImpl, UserTypeRepository and  UserTypeNotFoundException update RestExceptionHandler add script to insert usertypes.

2024-04-02 14:35 UTC, elbarbaro requested changes

2024-04-02 14:35 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/UserController.java
> +    UserService userService;
No olvidar el modificador de acceso

2024-04-02 14:35 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/UserController.java
> +    @PostMapping(path = "/users")
El mapping del nombre del recurso tiene mejor lugar en la definición de la anotación a nivel de la clase con una anotación específica. De esta forma todos lo métodos dentro de la clase seguiran el mismo nombre de recurso `/users` y sólo es separar por el tipo de método HTTP y no repetirlo.

En un desarrollo futuro, se tendría de nuevo que poner el nombre del recurso, esto sería repetirlo. La practica del uso de estas anotaciones de Spring Web sugiere una forma diferente.

2024-04-02 14:35 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/responses/UserResponse.java
> +    private String userType;
Sería mejor hacer uso de una clase enum con los tipos

2024-04-02 14:35 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/UserServiceImpl.java
> +        User user = new User();
Es una mejor practica crear la instancia una vez que se asegura que el user type existe. De esta forma creamos un objeto que será inicializado con todos sus valores

2024-04-02 14:35 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/UserServiceImpl.java
> +    public UserResponse toUserResponse(User user) {
Este tipo de métodos que hacen un procesamiento interno puede ser privado para que sea nada más de uso exclusivo dentro de la clase

2024-04-02 14:35 UTC, elbarbaro commented on src/main/resources/migrations/V5.create_user.sql
> +)
Nos faltó un `;`

2024-04-02 14:35 UTC, elbarbaro commented on src/main/resources/migrations/V6.insert_user_types.sql
Las instrucciones de DML están bien. Estas pueden ser incluidas también en la misma migración donde se crean las tablas. Una vez que se define los esquemas luego el crear estos registros

2024-04-02 14:35 UTC, elbarbaro commented on src/main/resources/migrations/V6.insert_user_types.sql
> +('admin','this user has been created with all permissions','ACTIVE','2023-11-22 13:17:38.338333','2023-11-22 13:17:38.338333','null'),
Las fechas se podrían poner de manera automática al momento de que se ejecuten las instrucciones. Es recomendable usar funciones incorporadas del SGBD para consultar la fecha.

2024-04-17 02:57 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/responses/UserResponse.java
> +    private String userType;
entonces seria crear una clase enume como "UserTypes", ya que la clase que se mapea con la table se llama UserTypes?, este valor quedaria registrado en el campo "name" de la tabla user_types?

2024-04-17 02:57 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/UserController.java
> +    UserService userService;
corregido

2024-04-17 02:58 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/UserController.java
> +    @PostMapping(path = "/users")
corregido

2024-04-17 02:59 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/services/UserServiceImpl.java
> +    public UserResponse toUserResponse(User user) {
corregido

2024-04-17 03:10 UTC, raisa16 commented on src/main/resources/migrations/V5.create_user.sql
> +)
si se agrega el ; aun  se ejecutaria el segundo script ?

2024-04-17 03:23 UTC, raisa16 commented on src/main/resources/migrations/V5.create_user.sql
> +)
corregido

2025-01-02 00:37 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/services/UserServiceImpl.java
> +        com.nurserygarden.ecommerceapp.repositories.entities.UserType userType = userTypeRepository.findById(userDto.getUserTypeId()).orElseThrow(UserTypeNotFoundException::new);
Estamos duplicando la lógica que está en el UserTypeServiceImpl que es la misma comprobación de la existencia del tipo de usuario. La recomendación es utilizar ese componente en UserServiceImpl

2025-01-02 00:40 UTC, elbarbaro requested changes

2025-01-02 00:40 UTC, elbarbaro commented on src/main/resources/migrations/V5.create_user.sql
> +('user','this user has basic permissions','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Este tipo no existe. Para mas referencia está la enumeración que se creo de UserType

2025-01-02 00:50 UTC, elbarbaro requested changes

2025-01-02 00:50 UTC, elbarbaro commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/responses/UserType.java
> +public enum UserType {
UserTypeValue sería un nombre para esta clase enum, para que no tenga conflicto con la clase de entidad UserType

2025-01-04 03:17 UTC, raisa16 commented on src/main/resources/migrations/V5.create_user.sql
> +('user','this user has basic permissions','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
El tipo fue remplazado por 'CLIENT' de acuerdo a los tipos de usuarios permitidos

2025-01-04 03:17 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/controllers/responses/UserType.java
> +public enum UserType {
El nombre se actualizo a UserTypeValue

2025-01-04 03:28 UTC, raisa16 commented on src/main/java/com/nurserygarden/ecommerceapp/services/UserServiceImpl.java
> +        com.nurserygarden.ecommerceapp.repositories.entities.UserType userType = userTypeRepository.findById(userDto.getUserTypeId()).orElseThrow(UserTypeNotFoundException::new);
Se remplazo la logica para hacer uso de la excistente en UserTypeServiceImpl

2025-01-06 01:54 UTC, elbarbaro approved these changes

2025-01-06 23:07 UTC, merged